name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: npm install, build
        run: |
          npm ci
          npm run build
          touch ./dist/.nojekyll
          sed -i '/\/dist/d' .gitignore
          echo "cyclorama.leifgehrmann.com" >> ./dist/CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
